#ifndef _SEKAI_ENGINE_CONFIG_VERSION_H_
#define _SEKAI_ENGINE_CONFIG_VERSION_H_

#define SEKAI_ENGINE_VERSION "@PROJECT_VERSION@"
#define SEKAI_ENGINE_VERSION_MAJOR "@PROJECT_VERSION_MAJOR@"
#define SEKAI_ENGINE_VERSION_MINOR "@PROJECT_VERSION_MINOR@"
#define SEKAI_ENGINE_VERSION_PATCH "@PROJECT_VERSION_PATCH@"

#endif //!_SEKAI_ENGINE_CONFIG_VERSION_H_