name: Build Web App
run-name: ${{ github.ref }} on ${{ github.repository }} is built for Web app
on: [push]
jobs:
    Build-WebApp:
        runs-on: "ubuntu-latest"
        steps:
            - name: Check out the repository code
              uses: actions/checkout@v4
            - name: Setup emsdk
              uses: mymindstorm/setup-emsdk@v14
              with:
                version: 3.1.25
                actions-cache-folder: 'emsdk-cache'
            - name: setup library
              run: /bin/bash ./NeoSekaiEngine/scripts/pre-installer/linux/debian/preinstaller.sh
            - name: Generate project for BUILD_SHARED_LIBS=0 
              run: cmake -S . -B build -DPLATFORM=Web -DBUILD_SHARED_LIBS=0 -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
            - name: Build project
              run: cmake --build ./build --config Release
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '21'
            - name: Install dependencies
              run: npm install --prefix ./TicTacToeWebApp && npm run install-wasm --prefix ./TicTacToeWebApp
            - name: Build
              run: npm run build --prefix ./TicTacToeWebApp
            - name: 🚀Deploy to GitHub Pages🚀  // --> this deploys to gh-pages
              if: github.ref == 'refs/heads/main'
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./TicTacToeWebApp/dist
            